### PR TITLE
Improve flexibility of functions

### PR DESCRIPTION
**Pull request by wijagels**
This adds additional kwargs that shouldn't affect existing users, but at the same time adds more ability to control data coming from zenoss.

### CODE REVIEW

**Comment by jackfischer** [comment]
+1, this would be helpful

**Comment by elanger4** [comment]
Imagine this was merged. Isn't that a wild idea?

**Comment by nvander1** [comment]
More kwargs the better. +1

**Comment by iamseth** [comment]
for some reason I never get emails about PRs. sorry for being late to this.

**Pull request merged**
